"""
observability.py — لاگ ساختاریافته و ردیابی خطا
Structured JSON logging, request ids, and Sentry.

WHAT THIS REPLACES

The application reported problems with print(): `[db] refresh … failed`,
`[cache] Redis unavailable`, and a `[perf]` line for any request over 200 ms.
Printed lines are fine when one process writes to one terminal. Across six
containers, four Gunicorn workers and a Celery pool they are unsearchable and
uncorrelatable — there is no way to ask "what else happened during the request
that took 4 seconds?" because nothing ties the lines together.

Every log line is now a single-line JSON object carrying a request id, and that
id is generated by nginx, passed through as X-Request-ID, attached to every
record emitted while handling the request, and returned to the client in the
response header. One grep on that id gives the whole story of one request across
every process that touched it.

WHAT IS DELIBERATELY NOT LOGGED

  * Cookies and Authorization headers — never, in any form. The session cookie
    is a bearer credential; a log that contains it is a log that can impersonate.
  * Request bodies and query strings. The query string is where the Persian
    user data lives: /stocks?group=فلزات اساسی, the watchlist ticker, the search
    term. The PATH is logged, the query is not.
  * Usernames and e-mail addresses. Records carry the numeric user id when there
    is one, which is enough to correlate and does not identify anyone in a log
    shipped elsewhere.

Sentry follows the same rule: send_default_pii is off and a scrubber strips
what the SDK collects by default.
"""
import json
import logging
import os
import sys
import time
import traceback
import uuid
from contextvars import ContextVar

# The current request's id. A ContextVar rather than a thread-local because
# Gunicorn runs gthread workers — several requests share a process — and a
# module-level global would leak one request's id into another's log lines.
_request_id: ContextVar = ContextVar("request_id", default=None)

SERVICE = os.environ.get("SERVICE_NAME", "boursenegar")
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
# JSON everywhere by default; set LOG_FORMAT=text for a readable local console.
LOG_FORMAT = os.environ.get("LOG_FORMAT", "json").lower()

# The threshold order 00 established and this order keeps: a request over this
# many milliseconds is a WARNING, not an INFO line.
SLOW_REQUEST_MS = float(os.environ.get("SLOW_REQUEST_MS", "200"))

# Headers that must never reach a log or an error report.
_REDACTED_HEADERS = {"cookie", "set-cookie", "authorization", "proxy-authorization",
                     "x-api-key", "x-csrf-token"}

_LOGRECORD_STANDARD = set(vars(logging.LogRecord("", 0, "", 0, "", (), None)))


def request_id():
    return _request_id.get()


def set_request_id(value=None):
    """Adopt an incoming id or mint one. Returns the id in force."""
    rid = (value or uuid.uuid4().hex[:16]).strip()[:64]
    _request_id.set(rid)
    return rid


class JsonFormatter(logging.Formatter):
    """One JSON object per line.

    Hand-written rather than pulled from a dependency: the whole formatter is
    forty lines, and it keeps the redaction rules in the same file as the policy
    they implement."""

    def format(self, record):
        payload = {
            "ts": time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(record.created))
                  + f".{int(record.msecs):03d}Z",
            "level": record.levelname,
            "logger": record.name,
            "service": SERVICE,
            "msg": record.getMessage(),
        }
        rid = getattr(record, "request_id", None) or _request_id.get()
        if rid:
            payload["request_id"] = rid
        if record.exc_info:
            payload["exc_type"] = record.exc_info[0].__name__
            payload["exc"] = "".join(
                traceback.format_exception(*record.exc_info))[-4000:]

        # Anything passed as extra={...}, minus the standard LogRecord fields.
        for key, value in vars(record).items():
            if key in _LOGRECORD_STANDARD or key in payload or key.startswith("_"):
                continue
            if key in ("args", "msg", "exc_info", "exc_text", "stack_info",
                       "taskName"):
                continue
            payload[key] = _safe(value)

        # ensure_ascii=False so Persian text stays readable rather than turning
        # into \uXXXX escapes in the log.
        return json.dumps(payload, ensure_ascii=False, default=str)


class TextFormatter(logging.Formatter):
    """Console format for local development."""

    def format(self, record):
        rid = getattr(record, "request_id", None) or _request_id.get()
        head = f"{record.levelname:<7} {record.name}"
        if rid:
            head += f" [{rid}]"
        out = f"{head}  {record.getMessage()}"
        if record.exc_info:
            out += "\n" + "".join(traceback.format_exception(*record.exc_info))
        return out


def _safe(value):
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if isinstance(value, (list, tuple)):
        return [_safe(v) for v in value]
    if isinstance(value, dict):
        return {k: ("[redacted]" if str(k).lower() in _REDACTED_HEADERS else _safe(v))
                for k, v in value.items()}
    return str(value)


_configured = False


def setup_logging(level=None):
    """Install the formatter on the root logger. Idempotent — app.py, the Celery
    worker and Beat all call it."""
    global _configured
    if _configured:
        return logging.getLogger(SERVICE)

    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(JsonFormatter() if LOG_FORMAT == "json" else TextFormatter())

    root = logging.getLogger()
    # Replace rather than add: Flask/Celery/gunicorn each install their own, and
    # leaving them attached prints every line twice, once unformatted.
    for existing in list(root.handlers):
        root.removeHandler(existing)
    root.addHandler(handler)
    root.setLevel(level or LOG_LEVEL)

    # These are noisy and say nothing the access log does not.
    logging.getLogger("werkzeug").setLevel("WARNING")
    logging.getLogger("urllib3").setLevel("WARNING")
    # Gunicorn's own loggers must propagate to root, or its access lines stay
    # plain text while everything else is JSON.
    for name in ("gunicorn.error", "gunicorn.access", "celery", "celery.app.trace"):
        lg = logging.getLogger(name)
        lg.handlers = []
        lg.propagate = True

    _configured = True
    return logging.getLogger(SERVICE)


def get_logger(name=None):
    return logging.getLogger(name or SERVICE)


# ---------------------------------------------------------------------------
# Sentry
# ---------------------------------------------------------------------------
def setup_sentry(component="web"):
    """Initialise Sentry if a DSN is configured. Returns True when enabled.

    A NOTE ON HOSTING. sentry.io is a foreign SaaS and this platform is deployed
    inside Iran, where reaching it is unreliable and where sending user traffic
    metadata abroad may not be acceptable. Sentry's server is open source, and
    GlitchTip speaks the same protocol in a fraction of the footprint — either
    can be run on the same VPS and pointed at with SENTRY_DSN. Nothing here
    assumes the hosted service.

    With no DSN this is a silent no-op, so a deployment that does not want error
    tracking simply leaves the variable empty."""
    dsn = (os.environ.get("SENTRY_DSN") or "").strip()
    if not dsn:
        return False
    try:
        import sentry_sdk
        from sentry_sdk.integrations.logging import LoggingIntegration
    except ImportError:
        get_logger().warning("SENTRY_DSN is set but sentry-sdk is not installed")
        return False

    integrations = [LoggingIntegration(level=logging.INFO,        # breadcrumbs
                                       event_level=logging.ERROR)]  # events
    try:
        if component == "web":
            from sentry_sdk.integrations.flask import FlaskIntegration
            integrations.append(FlaskIntegration())
        else:
            from sentry_sdk.integrations.celery import CeleryIntegration
            integrations.append(CeleryIntegration())
    except ImportError:
        pass

    sentry_sdk.init(
        dsn=dsn,
        environment=os.environ.get("APP_ENV", "development"),
        release=os.environ.get("APP_RELEASE") or None,
        integrations=integrations,
        # OFF. With it on the SDK attaches cookies, the request body and the
        # user's IP to every event — exactly the three things this module exists
        # to keep out of the record.
        send_default_pii=False,
        traces_sample_rate=float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "0")),
        before_send=_scrub_event,
        max_breadcrumbs=30,
    )
    sentry_sdk.set_tag("component", component)
    return True


def _scrub_event(event, hint):
    """Last line of defence before an event leaves the process.

    send_default_pii=False already prevents most of this; doing it again here
    means a future integration that collects something new cannot leak it by
    default."""
    req = event.get("request") or {}
    headers = req.get("headers") or {}
    for name in list(headers):
        if name.lower() in _REDACTED_HEADERS:
            headers[name] = "[redacted]"
    # The query string carries the Persian filter values and search terms.
    req.pop("query_string", None)
    req.pop("data", None)
    req.pop("cookies", None)
    if req:
        event["request"] = req
    # Keep the numeric id for correlation, drop everything that identifies.
    user = event.get("user") or {}
    event["user"] = {"id": user.get("id")} if user.get("id") else {}
    return event


# ---------------------------------------------------------------------------
# Flask wiring
# ---------------------------------------------------------------------------
def init_app(flask_app):
    """Attach request-id handling and the slow-request warning to a Flask app.

    Replaces the _perf_start/_perf_log pair that printed
    `[perf] GET /stocks -> 200 4231ms`."""
    from flask import g, request

    setup_logging()
    log = get_logger("boursenegar.request")

    @flask_app.before_request
    def _start_request():
        # nginx sets X-Request-ID from its own $request_id, so the id in the
        # nginx access log and the id in these records are the same string.
        g._request_id = set_request_id(request.headers.get("X-Request-ID"))
        g._t0 = time.perf_counter()

    @flask_app.after_request
    def _finish_request(response):
        t0 = getattr(g, "_t0", None)
        if t0 is None:
            return response
        ms = (time.perf_counter() - t0) * 1000.0
        rid = getattr(g, "_request_id", None)
        if rid:
            # Hand the id back so a user reporting a problem can quote it.
            response.headers["X-Request-ID"] = rid

        # The 200 ms threshold from order 00, kept as the order requires — but
        # as a structured warning-level event rather than a printed line.
        slow = ms >= SLOW_REQUEST_MS
        if slow or response.status_code >= 500:
            log.warning(
                "slow request" if slow else "request failed",
                extra={
                    "http_method": request.method,
                    # PATH only. The query string holds the Persian filter
                    # values, the search term and the watchlist ticker.
                    "http_path": request.path,
                    "status": response.status_code,
                    "duration_ms": round(ms, 1),
                    "threshold_ms": SLOW_REQUEST_MS,
                    "endpoint": request.endpoint,
                    "user_id": _current_user_id(),
                },
            )
        return response

    @flask_app.teardown_request
    def _clear_request(exc=None):
        _request_id.set(None)

    return flask_app


def _current_user_id():
    """The numeric id only — never the username or e-mail."""
    try:
        from flask_login import current_user
        if getattr(current_user, "is_authenticated", False):
            return getattr(current_user, "id", None)
    except Exception:
        pass
    return None
