#!/bin/sh
# entrypoint.sh — make sure nginx has a certificate before it starts.
#
# nginx refuses to start at all if ssl_certificate points at a missing file, so
# a first `docker compose up` on a fresh host would fail with a confusing error
# rather than a working (if untrusted) site. This generates a self-signed pair
# on the tls volume when none is present. Replacing those two files with a real
# certificate and reloading is the entire upgrade path — no config change.
set -eu

TLS_DIR=/etc/nginx/tls
CERT="$TLS_DIR/fullchain.pem"
KEY="$TLS_DIR/privkey.pem"
CN="${TLS_SELF_SIGNED_CN:-localhost}"

if [ ! -s "$CERT" ] || [ ! -s "$KEY" ]; then
    echo "[nginx] no certificate in $TLS_DIR — generating a self-signed one for '$CN'."
    echo "[nginx] REPLACE IT before going live: browsers will warn on every visit,"
    echo "[nginx] and HSTS stays off automatically while the certificate is"
    echo "[nginx] self-signed (see below)."
    mkdir -p "$TLS_DIR"
    openssl req -x509 -nodes -newkey rsa:2048 -days 825 \
        -subj "/CN=$CN" \
        -addext "subjectAltName=DNS:$CN,DNS:localhost,IP:127.0.0.1" \
        -keyout "$KEY" -out "$CERT" 2>/dev/null
    chmod 600 "$KEY"
    chmod 644 "$CERT"
fi

# ---------------------------------------------------------------------------
# HSTS — decided from the certificate that is actually present.
#
# Strict-Transport-Security was previously a commented-out line in
# snippets/security-headers.conf with a note to uncomment it once a real
# certificate was installed. That is a manual step nobody performs, and it
# guards the wrong thing: the header is unsafe with a self-signed certificate
# (the browser pins the host to HTTPS for a year and drops the "proceed anyway"
# escape hatch) and correct with a CA-issued one. Which of those is on the
# volume is a run-time fact, so it is decided here.
#
# Self-signed is detected by issuer == subject, which is what self-signed
# MEANS, rather than by guessing from the filename or from whether this script
# generated it — the certificate may have been replaced on the volume since.
# ---------------------------------------------------------------------------
HSTS_FILE="/etc/nginx/snippets/hsts.conf"
HSTS_ENABLED="${HSTS_ENABLED:-auto}"
HSTS_MAX_AGE="${HSTS_MAX_AGE:-31536000}"

hsts_decision="off"
case "$HSTS_ENABLED" in
    1|true|yes|on)
        hsts_decision="on"
        why="HSTS_ENABLED=$HSTS_ENABLED"
        ;;
    0|false|no|off)
        hsts_decision="off"
        why="HSTS_ENABLED=$HSTS_ENABLED"
        ;;
    *)
        subject=$(openssl x509 -in "$CERT" -noout -subject 2>/dev/null | sed 's/^subject=//') || subject=""
        issuer=$(openssl x509 -in "$CERT" -noout -issuer 2>/dev/null | sed 's/^issuer=//') || issuer=""
        if [ -n "$subject" ] && [ "$subject" = "$issuer" ]; then
            hsts_decision="off"
            why="certificate is self-signed"
        elif [ -n "$issuer" ]; then
            hsts_decision="on"
            why="certificate issued by: $issuer"
        else
            # Could not read the certificate at all. Refusing to send the header
            # is the recoverable choice; sending it on a guess is not.
            hsts_decision="off"
            why="could not read the certificate — staying off"
        fi
        ;;
esac

{
    echo "# GENERATED by entrypoint.sh at container start — do not edit."
    echo "# decision: $hsts_decision ($why)"
    if [ "$hsts_decision" = "on" ]; then
        echo "add_header Strict-Transport-Security \"max-age=${HSTS_MAX_AGE}; includeSubDomains\" always;"
    else
        echo "# (no Strict-Transport-Security header)"
    fi
} > "$HSTS_FILE"

echo "[nginx] HSTS $hsts_decision — $why"

# Validate before handing over: a bad config should fail here with a readable
# message rather than half-starting.
nginx -t

exec "$@"
